import { buildDefaultSourceLinks, slugify } from "@/lib/place-utils"
import type { Collection, Place } from "@/lib/types"

type SeedInput = Omit<
  Place,
  "id" | "slug" | "sourceLinks" | "publishedAt" | "gallery"
> & {
  id: string
  publishedAt?: string
  sourceLinks?: Place["sourceLinks"]
  gallery?: string[]
}

function makePlace(input: SeedInput): Place {
  return {
    ...input,
    slug: slugify(input.name),
    sourceLinks: input.sourceLinks ?? buildDefaultSourceLinks(input.name, input.city),
    publishedAt: input.publishedAt ?? "2026-05-01T08:00:00.000Z",
    gallery: input.gallery ?? [],
  }
}

export const SEED_COLLECTIONS: Collection[] = [
  {
    id: "rainy-cafes",
    slug: "rainy-day-cafes",
    city: "shanghai",
    title: "下雨天咖啡馆",
    description: "给阴天、耳机和缓慢下午准备的一组安静坐标。",
    theme: "Rainy-Day Ritual",
    placeIds: ["p-02", "p-08", "p-14", "p-20"],
    moodTags: ["rainy_day", "relaxed", "solo"],
  },
  {
    id: "date-night",
    slug: "date-night-loop",
    city: "shanghai",
    title: "约会夜路线",
    description: "从一顿认真晚餐到散步、夜景和收尾的一杯酒。",
    theme: "After-Dark Date Loop",
    placeIds: ["p-04", "p-09", "p-13", "p-15"],
    moodTags: ["date", "photo_friendly"],
  },
  {
    id: "design-weekend",
    slug: "design-weekend",
    city: "shanghai",
    title: "设计周末",
    description: "把展览、器物店、书店和城市散步串成一个完整下午。",
    theme: "Design Weekend",
    placeIds: ["p-05", "p-10", "p-11", "p-16", "p-17"],
    moodTags: ["photo_friendly", "friends"],
  },
  {
    id: "slow-shanghai",
    slug: "slow-shanghai",
    city: "shanghai",
    title: "慢一点的上海",
    description: "适合独处、观察路人和把节奏放慢的低刺激路线。",
    theme: "Slow Shanghai",
    placeIds: ["p-01", "p-03", "p-06", "p-18", "p-19"],
    moodTags: ["relaxed", "solo"],
  },
  {
    id: "gz-rainy-cafes",
    slug: "guangzhou-rainy-day-cafes",
    city: "guangzhou",
    title: "东山口雨天咖啡馆",
    description: "给潮湿空气、玻璃窗和慢慢坐下来的下午准备的一组广州坐标。",
    theme: "Guangzhou Rainy-Day Ritual",
    placeIds: ["p-21", "p-24"],
    moodTags: ["rainy_day", "relaxed", "solo"],
  },
  {
    id: "gz-date-night",
    slug: "zhujiang-date-night",
    city: "guangzhou",
    title: "珠江夜约会",
    description: "从看展、看江景到深夜一杯酒，把广州夜色连成一条线。",
    theme: "Pearl River Date Loop",
    placeIds: ["p-23", "p-27", "p-29"],
    moodTags: ["date", "photo_friendly"],
  },
  {
    id: "gz-design-weekend",
    slug: "guangzhou-design-weekend",
    city: "guangzhou",
    title: "广州设计周末",
    description: "把买手店、展览和旧城更新空间串成一整个下午。",
    theme: "Guangzhou Design Weekend",
    placeIds: ["p-27", "p-28", "p-30"],
    moodTags: ["photo_friendly", "friends"],
  },
  {
    id: "slow-guangzhou",
    slug: "slow-guangzhou",
    city: "guangzhou",
    title: "慢一点的广州",
    description: "适合散步、吃碗热汤、看江风和把节奏放慢的一组城市片段。",
    theme: "Slow Guangzhou",
    placeIds: ["p-22", "p-23", "p-25", "p-26"],
    moodTags: ["relaxed", "solo", "friends"],
  },
]

export const SEED_PLACES: Place[] = [
  makePlace({
    id: "p-01",
    name: "安福公社食堂",
    category: "food",
    city: "shanghai",
    area: "安福路",
    address: "安福路 221 号，近武康路",
    lat: 31.2141,
    lng: 121.4468,
    priceLevel: "$$",
    tags: ["早午餐", "街景位", "适合聊天"],
    vibes: ["bright", "weekend", "people-watching"],
    summary: "一间适合把午后延长的街角厨房，面包香和阳光都来得很准时。",
    description:
      "CityTaste 把它放进慢速周末路线里：不一定是最网红的一家，但它给安福路提供了很好的开场。",
    statusDefault: "want_to_go",
    collectionIds: ["slow-shanghai"],
  }),
  makePlace({
    id: "p-02",
    name: "武康烘焙档案",
    category: "cafe",
    city: "shanghai",
    area: "武康路",
    address: "武康路 98 号，二层靠窗",
    lat: 31.2104,
    lng: 121.4378,
    priceLevel: "$$",
    tags: ["手冲", "靠窗位", "适合看书"],
    vibes: ["quiet", "editorial", "rainy-day"],
    summary: "像一本摊开的杂志，适合带着笔记本坐一整个雨天。",
    description:
      "木色、布面椅和有节制的音乐让它很适合作为个人城市地图里的深呼吸据点。",
    coverImage:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["rainy-cafes"],
  }),
  makePlace({
    id: "p-03",
    name: "空场小馆",
    category: "bar",
    city: "shanghai",
    area: "衡山路",
    address: "衡山路 115 号，地下室入口",
    lat: 31.2062,
    lng: 121.4402,
    priceLevel: "$$$",
    tags: ["鸡尾酒", "低光线", "适合收尾"],
    vibes: ["moody", "late-night", "soft-jazz"],
    summary: "没有过度表演的酒吧，更像一间会替夜晚收边的房间。",
    description:
      "对于约会夜或一个人的放空夜晚，它都比热闹更高级一点点。",
    statusDefault: "want_to_go",
    collectionIds: ["slow-shanghai", "date-night"],
  }),
  makePlace({
    id: "p-04",
    name: "目地画廊",
    category: "exhibition",
    city: "shanghai",
    area: "西岸",
    address: "西岸凤巢 B1，滨江步道旁",
    lat: 31.1755,
    lng: 121.4499,
    priceLevel: "$$",
    tags: ["摄影", "新媒体", "策展感"],
    vibes: ["minimal", "design", "afternoon"],
    summary: "适合和一个认真看展的人一起去，讨论会自然发生。",
    description:
      "它不是那种靠打卡装置撑起全部体验的空间，更像一段完整的观看路径。",
    coverImage:
      "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "visited",
    collectionIds: ["date-night", "design-weekend"],
  }),
  makePlace({
    id: "p-05",
    name: "华山手动供给",
    category: "shopping",
    city: "shanghai",
    area: "愚园路",
    address: "愚园路 1310 弄，小院深处",
    lat: 31.2245,
    lng: 121.4281,
    priceLevel: "$$",
    tags: ["器物", "家居", "礼物灵感"],
    vibes: ["curated", "soft-color", "design"],
    summary: "一间会让人想慢慢摸每件物件材质的设计小店。",
    description:
      "如果你的城市探索不仅是吃喝，它会证明生活方式店铺也值得被纳入地图。",
    coverImage:
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["design-weekend"],
  }),
  makePlace({
    id: "p-06",
    name: "苏河跑步俱乐部",
    category: "activity",
    city: "shanghai",
    area: "苏河湾",
    address: "苏河湾万象天地北侧集合点",
    lat: 31.2442,
    lng: 121.4705,
    priceLevel: "$",
    tags: ["跑步", "晨间", "城市路线"],
    vibes: ["fresh-air", "active", "community"],
    summary: "一条把城市从雾气里慢慢跑醒的晨间路线。",
    description:
      "它让 CityTaste 的地图不是只有消费场景，也包含一种可重复的城市使用方式。",
    statusDefault: "visited",
    collectionIds: ["slow-shanghai"],
  }),
  makePlace({
    id: "p-07",
    name: "静安面馆研究所",
    category: "food",
    city: "shanghai",
    area: "静安寺",
    address: "南京西路支巷 36 号",
    lat: 31.2232,
    lng: 121.4456,
    priceLevel: "$",
    tags: ["面馆", "深夜友好", "热汤"],
    vibes: ["comfort", "late-lunch", "unfussy"],
    summary: "好吃得没有废话，适合一个人快速把一天接回来。",
    description:
      "它是那种不会出现在大多数攻略首页，却会被朋友反复私下推荐的店。",
    statusDefault: "visited",
    collectionIds: ["slow-shanghai"],
  }),
  makePlace({
    id: "p-08",
    name: "愚园读书房",
    category: "cafe",
    city: "shanghai",
    area: "愚园路",
    address: "愚园路 1098 号，三楼",
    lat: 31.2248,
    lng: 121.4263,
    priceLevel: "$$",
    tags: ["书架", "插座多", "适合工作"],
    vibes: ["quiet", "study", "rainy-day"],
    summary: "介于书店和咖啡馆之间，工作时也会觉得自己很体面。",
    description:
      "如果你想把探索做得更日常，这种可停留的场所会比一次性打卡更重要。",
    coverImage:
      "https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["rainy-cafes"],
  }),
  makePlace({
    id: "p-09",
    name: "北外滩天际酒吧",
    category: "bar",
    city: "shanghai",
    area: "北外滩",
    address: "东大名路 999 号，高区露台",
    lat: 31.2512,
    lng: 121.5013,
    priceLevel: "$$$",
    tags: ["夜景", "露台", "约会"],
    vibes: ["glam", "night-view", "dramatic"],
    summary: "如果想把城市天际线纳入约会节奏，这里几乎不用额外修辞。",
    description:
      "适合作为一条夜晚路线的高潮点，在地图上它像一个会发光的 pin。",
    coverImage:
      "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "want_to_go",
    collectionIds: ["date-night"],
  }),
  makePlace({
    id: "p-10",
    name: "设计共和国工坊",
    category: "shopping",
    city: "shanghai",
    area: "新天地",
    address: "新天地时尚 II，2F",
    lat: 31.2183,
    lng: 121.4736,
    priceLevel: "$$$",
    tags: ["家具", "灯具", "设计品牌"],
    vibes: ["precise", "tasteful", "gallery-like"],
    summary: "既像商店，也像一个把生活方式摆上展台的策展空间。",
    description:
      "对于作品集来说，这种跨在 retail 和 exhibition 之间的场所很有产品叙事价值。",
    statusDefault: "want_to_go",
    collectionIds: ["design-weekend"],
  }),
  makePlace({
    id: "p-11",
    name: "Fotografiska 上海摄影中心",
    category: "exhibition",
    city: "shanghai",
    area: "苏河湾",
    address: "光复路 127 号",
    lat: 31.2454,
    lng: 121.4763,
    priceLevel: "$$",
    tags: ["摄影", "讲座", "城市文化"],
    vibes: ["immersive", "contemporary", "social"],
    summary: "一个会让展览、餐饮和社交边界变得柔软的文化据点。",
    description:
      "它很适合放进 CityTaste，因为这里本身就在演示什么叫 lifestyle mix。",
    coverImage:
      "https://images.unsplash.com/photo-1501612780327-45045538702b?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "visited",
    collectionIds: ["design-weekend"],
  }),
  makePlace({
    id: "p-12",
    name: "哥伦比亚圈慢集",
    category: "activity",
    city: "shanghai",
    area: "哥伦比亚圈",
    address: "延安西路 1262 号，草坪周边",
    lat: 31.2113,
    lng: 121.4158,
    priceLevel: "$",
    tags: ["周末集市", "遛狗", "轻社交"],
    vibes: ["open-air", "weekend", "casual"],
    summary: "适合什么都不买也愿意待上一小时的周末集市。",
    description:
      "这个点让地图从静态地点延展到了时间性的城市活动。",
    statusDefault: "visited",
    collectionIds: ["design-weekend"],
  }),
  makePlace({
    id: "p-13",
    name: "新天地黄油饼桌",
    category: "food",
    city: "shanghai",
    area: "新天地",
    address: "马当路 245 号，石库门转角",
    lat: 31.2177,
    lng: 121.4728,
    priceLevel: "$$",
    tags: ["小酒馆", "约会餐厅", "暖色灯光"],
    vibes: ["intimate", "date-night", "warm"],
    summary: "不会太拘谨，却足够认真，是很适合约会开场的一餐。",
    description:
      "它让新天地从游客区变成一个可以重新个人化理解的城市片段。",
    coverImage:
      "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["date-night"],
  }),
  makePlace({
    id: "p-14",
    name: "乒乓咖啡实验室",
    category: "cafe",
    city: "shanghai",
    area: "静安寺",
    address: "常德路 812 号，小院旁",
    lat: 31.2222,
    lng: 121.4388,
    priceLevel: "$$",
    tags: ["精品咖啡", "工作友好", "简洁空间"],
    vibes: ["clean", "focused", "rainy-day"],
    summary: "一间让人自动把通知静音的咖啡店。",
    description:
      "如果你想在产品里表达专注和秩序，这类点位非常适合做品牌样本。",
    coverImage:
      "https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "want_to_go",
    collectionIds: ["rainy-cafes"],
  }),
  makePlace({
    id: "p-15",
    name: "Candor 夜话沙龙",
    category: "bar",
    city: "shanghai",
    area: "愚园路",
    address: "愚园路 1000 弄，黑门内",
    lat: 31.224,
    lng: 121.4302,
    priceLevel: "$$$",
    tags: ["live music", "香槟杯", "夜生活"],
    vibes: ["performative", "velvet", "after-dark"],
    summary: "介于酒吧和夜间沙龙之间，适合把夜晚留到更晚一些。",
    description:
      "它给 CityTaste 带来更有戏剧性的夜生活层次，而不是只有 rooftop clichés。",
    statusDefault: "want_to_go",
    collectionIds: ["date-night"],
  }),
  makePlace({
    id: "p-16",
    name: "洛克外滩艺术漫步",
    category: "exhibition",
    city: "shanghai",
    area: "北外滩",
    address: "虎丘路到圆明园路步行段",
    lat: 31.2405,
    lng: 121.4905,
    priceLevel: "$",
    tags: ["建筑", "画廊", "步行路线"],
    vibes: ["urban", "architectural", "golden-hour"],
    summary: "不是单点目的地，而是一段适合边走边看的城市艺术截面。",
    description:
      "它证明 collection 页面可以成立，因为有些推荐本来就更像一条线而不是一颗 pin。",
    coverImage:
      "https://images.unsplash.com/photo-1473773508845-188df298d2d1?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "visited",
    collectionIds: ["design-weekend"],
  }),
  makePlace({
    id: "p-17",
    name: "地铁市集档案店",
    category: "shopping",
    city: "shanghai",
    area: "苏河湾",
    address: "天潼路旧仓库改造空间",
    lat: 31.2449,
    lng: 121.4851,
    priceLevel: "$$",
    tags: ["杂志", "香氛", "家居小物"],
    vibes: ["editorial", "slow-retail", "curated"],
    summary: "像把一本生活方式杂志拆开摆成了实体空间。",
    description:
      "这种带有强烈品味过滤器的零售空间，非常适合成为作品集视觉重心。",
    coverImage:
      "https://images.unsplash.com/photo-1523381210434-271e8be1f52b?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["design-weekend"],
  }),
  makePlace({
    id: "p-18",
    name: "西岸江边骑行",
    category: "activity",
    city: "shanghai",
    area: "西岸",
    address: "龙腾大道滨江骑行段",
    lat: 31.1774,
    lng: 121.4508,
    priceLevel: "$",
    tags: ["骑行", "落日", "风大"],
    vibes: ["sunset", "open", "motion"],
    summary: "适合傍晚骑行，把展览和晚饭连成同一段周末叙事。",
    description:
      "它让地图里的 '玩' 不只是名词，还包含路径和节奏。",
    statusDefault: "want_to_go",
    collectionIds: ["slow-shanghai"],
  }),
  makePlace({
    id: "p-19",
    name: "老弄堂饺子摊",
    category: "food",
    city: "shanghai",
    area: "武康路",
    address: "湖南路支弄 12 号",
    lat: 31.2095,
    lng: 121.4355,
    priceLevel: "$",
    tags: ["本地味", "小店", "一人食"],
    vibes: ["comfort", "neighborhood", "quick-stop"],
    summary: "一间不会主动抢镜，却总能在散步路线里被记住的小店。",
    description:
      "这种轻量、邻里感强的点位能让 CityTaste 不至于只剩下精品化场景。",
    statusDefault: "visited",
    collectionIds: ["slow-shanghai"],
  }),
  makePlace({
    id: "p-20",
    name: "雨窗咖啡",
    category: "cafe",
    city: "shanghai",
    area: "安福路",
    address: "安福路 168 号，二层拐角窗边",
    lat: 31.2132,
    lng: 121.4455,
    priceLevel: "$$",
    tags: ["玻璃窗", "肉桂卷", "安静"],
    vibes: ["soft-light", "slow", "rainy-day"],
    summary: "如果要给阴雨天找一个视觉母题，大概就是这里的窗。",
    description:
      "它非常适合做首页的情绪锚点，因为名字和体验都天然有画面感。",
    coverImage:
      "https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["rainy-cafes"],
  }),
  makePlace({
    id: "p-21",
    name: "东山口临窗咖啡馆",
    category: "cafe",
    city: "guangzhou",
    area: "东山口",
    address: "庙前西街 18 号，骑楼二层窗边",
    lat: 23.1197,
    lng: 113.2956,
    priceLevel: "$$",
    tags: ["靠窗位", "适合工作", "街景"],
    vibes: ["quiet", "rainy-day", "editorial"],
    summary: "像把广州的湿热空气和老城区窗景一起端上桌的一间咖啡馆。",
    description:
      "东山口很适合做城市切换后的第一屏样本，因为它一眼就和上海的梧桐路段形成了不同节奏。",
    coverImage:
      "https://images.unsplash.com/photo-1497935586047-9392d6f4f638?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["gz-rainy-cafes"],
  }),
  makePlace({
    id: "p-22",
    name: "永庆煲仔小馆",
    category: "food",
    city: "guangzhou",
    area: "永庆坊",
    address: "恩宁路 227 号，转角骑楼下",
    lat: 23.1161,
    lng: 113.2384,
    priceLevel: "$$",
    tags: ["煲仔饭", "西关", "晚饭"],
    vibes: ["comfort", "neighborhood", "warm"],
    summary: "不需要太多包装，一口热气就能把广州的生活感拉到面前。",
    description:
      "如果上海路线像杂志感周末，广州这类点位会更像日常里随手就能抵达的真实烟火。",
    statusDefault: "want_to_go",
    collectionIds: ["slow-guangzhou"],
  }),
  makePlace({
    id: "p-23",
    name: "珠江日落骑行",
    category: "activity",
    city: "guangzhou",
    area: "琶醍",
    address: "阅江西路江边骑行段",
    lat: 23.1009,
    lng: 113.3456,
    priceLevel: "$",
    tags: ["骑行", "落日", "江风"],
    vibes: ["sunset", "open", "motion"],
    summary: "适合把江边落日和晚上的下一站连成同一段广州叙事。",
    description:
      "这个点让广州不只是吃喝目的地，也是一种可以在地图上被安排节奏的城市使用方式。",
    coverImage:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "visited",
    collectionIds: ["gz-date-night", "slow-guangzhou"],
  }),
  makePlace({
    id: "p-24",
    name: "天河阅读咖啡",
    category: "cafe",
    city: "guangzhou",
    area: "天河南",
    address: "体育东路支巷 26 号，三层安静区",
    lat: 23.1365,
    lng: 113.3278,
    priceLevel: "$$",
    tags: ["插座多", "适合学习", "安静"],
    vibes: ["study", "clean", "rainy-day"],
    summary: "在广州也能找到那种一坐下来就会自动把消息静音的工作型咖啡馆。",
    description:
      "它给双城系统补上了另一类节奏：不是慢逛，而是高密度城市中的短暂停靠。",
    statusDefault: "want_to_go",
    collectionIds: ["gz-rainy-cafes"],
  }),
  makePlace({
    id: "p-25",
    name: "沙面江边散步线",
    category: "activity",
    city: "guangzhou",
    area: "沙面",
    address: "沙面南街到白鹅潭步行段",
    lat: 23.1089,
    lng: 113.2437,
    priceLevel: "$",
    tags: ["散步", "老建筑", "树荫"],
    vibes: ["slow", "historic", "weekend"],
    summary: "适合什么都不安排得太满，只想沿着旧建筑和江边慢慢走一段。",
    description:
      "它能很好地说明 CityTaste 不是只有“店”，也包括更像城市片段的路线型体验。",
    statusDefault: "visited",
    collectionIds: ["slow-guangzhou"],
  }),
  makePlace({
    id: "p-26",
    name: "北京路夜宵小馆",
    category: "food",
    city: "guangzhou",
    area: "北京路",
    address: "惠福东路 92 号，夜市边角",
    lat: 23.1256,
    lng: 113.2707,
    priceLevel: "$",
    tags: ["夜宵", "碳水", "一个人吃也自在"],
    vibes: ["quick-stop", "late-night", "local"],
    summary: "不是精致路线里的主角，却很适合当成广州夜晚真正会发生的一顿。",
    description:
      "它让这套城市系统保留了“轻量、实用、不端着”的一面，而不是全部都做成精选清单。",
    statusDefault: "favorite",
    collectionIds: ["slow-guangzhou"],
  }),
  makePlace({
    id: "p-27",
    name: "K11 广州展厅",
    category: "exhibition",
    city: "guangzhou",
    area: "珠江新城",
    address: "珠江东路 6 号，展览楼层",
    lat: 23.1181,
    lng: 113.3276,
    priceLevel: "$$",
    tags: ["展览", "当代艺术", "室内空间"],
    vibes: ["minimal", "design", "afternoon"],
    summary: "适合和一个愿意认真看展的人一起去，把看展和夜晚的下一站接起来。",
    description:
      "它给广州这条线补上了更清晰的文化入口，也让双城切换后的内容层次更平衡。",
    coverImage:
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "want_to_go",
    collectionIds: ["gz-date-night", "gz-design-weekend"],
  }),
  makePlace({
    id: "p-28",
    name: "东山口选物屋",
    category: "shopping",
    city: "guangzhou",
    area: "东山口",
    address: "新河浦路 12 号，白楼一层",
    lat: 23.1206,
    lng: 113.2968,
    priceLevel: "$$",
    tags: ["买手店", "器物", "小众品牌"],
    vibes: ["curated", "soft-color", "design"],
    summary: "一间会让人想慢慢摸材质、顺手记下店名的生活方式小店。",
    description:
      "它能让广州的设计周末路线成立，不只是看展，也包括零售和街区气质本身。",
    coverImage:
      "https://images.unsplash.com/photo-1441986300917-64674bd600d8?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "favorite",
    collectionIds: ["gz-design-weekend"],
  }),
  makePlace({
    id: "p-29",
    name: "江景深夜酒吧",
    category: "bar",
    city: "guangzhou",
    area: "珠江新城",
    address: "临江大道 1 号，高层露台",
    lat: 23.1171,
    lng: 113.3301,
    priceLevel: "$$$",
    tags: ["夜景", "露台", "约会"],
    vibes: ["glam", "night-view", "after-dark"],
    summary: "如果想把广州夜景纳入一条约会路线，这里会是很自然的收尾。",
    description:
      "它和上海 rooftop 的感觉不同，更潮湿、更松弛，也更适合珠江这条线的城市节奏。",
    coverImage:
      "https://images.unsplash.com/photo-1516997121675-4c2d1684aa3e?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "want_to_go",
    collectionIds: ["gz-date-night"],
  }),
  makePlace({
    id: "p-30",
    name: "海珠阁楼摄影厅",
    category: "exhibition",
    city: "guangzhou",
    area: "海珠广场",
    address: "一德路旧仓库改造空间",
    lat: 23.1165,
    lng: 113.2683,
    priceLevel: "$$",
    tags: ["摄影", "旧城更新", "空间感"],
    vibes: ["architectural", "editorial", "urban"],
    summary: "在旧城和新展陈之间找到平衡的一类空间，很适合做广州线的视觉支点。",
    description:
      "如果要让双城切换不仅是换数据，也换气质，这类点位会比单纯复制咖啡馆更有效。",
    coverImage:
      "https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80",
    statusDefault: "visited",
    collectionIds: ["gz-design-weekend"],
  }),
]
